#!/bin/bash

if [[ "$1" == "serve" ]]; then
    docker run -it -e LOCAL_USER_ID=`id -u $USER` --rm -p 8000:8000 -p 35729:35729 -v ${PWD}:/project --name "superplusplus" superplusplus
else
    echo "Not sure what you want me to do."
fi
