#!/bin/bash

case "$1" in
    serve)
        docker run -it -e LOCAL_USER_ID=`id -u $USER` --rm -p 8000:8000 -p 35729:35729 -v ${PWD}:/project --name "superplusplus" superplusplus
        ;;
    bash)
        docker exec -it --user `id -u $USER` superplusplus bash
        ;;
    *)
        echo $"Usage: $0 {serve|bash}"
esac